{{- if .Values.ingressClass.create -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingressClass.name }}
  labels:
    {{- include "edgenexus-ingress.labels" . | nindent 4 }}
  {{- if .Values.ingressClass.isDefault }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  {{- end }}
spec:
  controller: edgenexus.io/ingress-controller
{{- end }}
