apiVersion: v1
kind: Service
metadata:
  name: {{ include "edgenexus-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgenexus-ingress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
  - port: {{ .Values.service.httpPort }}
    targetPort: 80
    protocol: TCP
    name: http
  - port: {{ .Values.service.httpsPort }}
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    {{- include "edgenexus-ingress.selectorLabels" . | nindent 4 }}
